### ISSUE TITLE
用 Github 账号登录

### ISSUE THREAD

**Issue by Kabie** [jw2013/elixir-china#42]
不过库的选择有点多：

https://hex.pm/packages?search=oauth

有人有使用过其中某个的经验么？

**Comment by jw2013** [comment]
@lidashuang @hisea @ruchee

**Comment by lidashuang** [comment]
自己写也挺简单的，也没有多少代码
我之前写的 
https://github.com/sdutlinux/slug/blob/master/lib/slug/github.ex
https://github.com/sdutlinux/slug/blob/master/web/controllers/sessions_controller.ex#L9-L28

**Comment by Kabie** [comment]
嗯，我之前把登录注册合成一个页面其实也是为这个做准备的

我理想的情况是废弃普通登录，只用Github

**Comment by lidashuang** [comment]
@Kabie 如果只用github的话倒是能省不少事情, 就是只用github的话处理现有的账号比较麻烦

**Comment by hisea** [comment]
我觉得直接写出来难度不大。

但是我想有没有什么更好的方式。把这部分逻辑搞出来。做成像Rails里面Devise或者Omni的组建。

对Phoenix了解还不是很多。有没有一个办法可以共享controller的？

**Comment by pynixwang** [comment]
omniauth

**Comment by songjiayang** [comment]
第一次注册就在想为什么没有github登录
