### ISSUE TITLE
1，发帖，错误提交没提示。2，发帖时间显示有误。

### ISSUE THREAD

**Issue by GaaraLi** [jw2013/elixir-china#43]

**Comment by jw2013** [comment]
1. 发帖，错误提交没提示

https://github.com/jw2013/elixir-china/commit/c159d55617be43641dffacbaabf2b8990027bc87 搞定了这个问题
2. 发帖时间显示有误

能不能问问错误具体是怎样的？多谢了！

**Comment by GaaraLi** [comment]
就是，显示在首页帖子下方的 几时几分 最后更新 这个，时间显示有误，目测是你时区换算错误了吧，你直接手动－16了吗？

--  
Leo
已使用 Sparrow (http://www.sparrowmailapp.com/?sig)

已使用 Sparrow (http://www.sparrowmailapp.com/?sig)  

在 2015年1月12日 星期一，下午3:42，Zhe Wang 写道：

**Comment by jw2013** [comment]
@GaaraLi 
哈哈 你发comment之前我已经修好了：
https://github.com/jw2013/elixir-china/commit/0f7dc9449f5c4f543b77a4fc497985edae0bba8a

重新加载下网站吧（不行的话清理下缓存）。告诉下我好了没有哈。多谢了。

**Comment by GaaraLi** [comment]
好像是好了哈。
你这使用Elixir的框架开发的吗？我爱莫能助，只能看看了，贡献不了代码。


--  
Leo
已使用 Sparrow (http://www.sparrowmailapp.com/?sig)

已使用 Sparrow (http://www.sparrowmailapp.com/?sig)  

在 2015年1月12日 星期一，下午4:34，Zhe Wang 写道：

**Comment by jw2013** [comment]
是的，我用Phoenix。

我刚开始写的时候毫无Phoenix的资料。现在很多很多了，你去这里稍微看看就会了：
http://www.phoenixframework.org/

不少地方很Rails很像的。 

希望早日能看见你贡献的代码。 :smile: 

:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by GaaraLi** [comment]
我大概看了一下源码，是很多地方挺相似的，不过目前在找工作，等找到了，抽空可以去看一下，能贡献代码当然也是荣幸之至。

--  
Leo
已使用 Sparrow (http://www.sparrowmailapp.com/?sig)

已使用 Sparrow (http://www.sparrowmailapp.com/?sig)  

在 2015年1月12日 星期一，下午4:38，Zhe Wang 写道：

**Comment by jw2013** [comment]
已经很感激你提的Issue了。希望你早日能找到你喜欢的工作。到时候等你的加入啦。

:whale:

**Comment by GaaraLi** [comment]
借你吉言哈！希望你们也越做越好？

--  
Leo
已使用 Sparrow (http://www.sparrowmailapp.com/?sig)

已使用 Sparrow (http://www.sparrowmailapp.com/?sig)  

在 2015年1月12日 星期一，下午4:43，Zhe Wang 写道：

**Comment by jw2013** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
