### ISSUE TITLE
登陆密码错误 

### ISSUE THREAD

**Issue by OhCoder** [jw2013/elixir-china#50]
刚才登录论坛，提示用户名不存在，随后添上用户名之后说密码错误。
最后想重新注册提示说邮箱已经占用……
请问怎么解决？

**Comment by hisea** [comment]
我怀疑是用户名大小写的问题。

**Comment by OhCoder** [comment]
大小写区分了一下，还是不行。

**Comment by jw2013** [comment]
现在可以你告诉我你的ID，我把这个ID删了你重新注册可以么？

下周末有空的时候我把邮箱重设密码的功能加上去。

**Comment by OhCoder** [comment]
我注册的邮箱是coderliang@gmail.com
用户名不记得了

**Comment by jw2013** [comment]
你的用户名是ohcoder

你用是用邮箱+密码登陆的，还是用户名+密码登陆的？应该是用户名+密码登陆。

如果你确定是用户名登陆的话我给你发个随机的密码让你先登进去改密码。

**Comment by OhCoder** [comment]
不记得有没有用户名，只知道邮箱被占用了。我注册的时候，使用新邮箱注册不了

**Comment by jw2013** [comment]
好的。你能不能试试用ohcoder作为登录名，加上你的密码登陆呢？

**Comment by OhCoder** [comment]
不行，提示我密码错误

**Comment by jw2013** [comment]
好吧。我删了你那邮箱的账号了，麻烦你重新注册个吧。

:smiley:

**Comment by OhCoder** [comment]
嗯，已经重新注册了。thanks
