### ISSUE TITLE
用户名最好不要区分大小写

### ISSUE THREAD

**Issue by hisea** [jw2013/elixir-china#51]
发现用户名区分大小写。我觉得比较麻烦，登陆容易造成困扰，也容易冒认身份。

**Comment by jw2013** [comment]
有道理。我觉得最好的解决方法是：

1)用户注册和显示的ID可以大小写。其一是已经有用户注册这样的ID了，第二的确有这样的需求，比如用户想注册ElixirChina这个名字因为更容易辨认，而不是elixirchina。也就是说存进数据库里的ID是有大小写的。

2)用户注册的时候，后台检测是否有一样的用户名的时候，不区分大小写。这样能解决“登陆容易造成困扰，也容易冒认身份”的问题。

貌似还要升级下ecto来完成unique(downcase: true)的支持

**Comment by conwqi1** [comment]
Jack, the authentication guru!
