### ISSUE TITLE
屏蔽垃圾广告的功能

### ISSUE THREAD

**Issue by jiyinyiyong** [jw2013/elixir-china#54]
首页被污染了啊
http://elixir-cn.com/

**Comment by jw2013** [comment]
多谢issue哈 已经删了。

如何屏蔽垃圾广告呢

**Comment by jiyinyiyong** [comment]
@jw2013 这个我不知道, 但是 CNode 这边经验可以参考下: https://github.com/cnodejs/nodeclub/issues/231 https://github.com/cnodejs/nodeclub/pull/373
有段时间被注册机发广告了, 于是加了一些发贴的限制, 以及完善了从 GitHub 注册的条件.
更有用的是增加了管理员屏蔽用户的功能, 剩下就是看到广告清理帖子干掉发帖人了.

**Comment by jw2013** [comment]
多谢多谢 觉得可以新用户刚注册完不能发帖 ;)

**Comment by zhangsoledad** [comment]
ruby china人比较多 内容也比较丰富了 那边是新注册用户一周内不能发帖 
以后这边人也多起来也可以这么搞
