### ISSUE TITLE
没有 RSS 输出

### ISSUE THREAD

**Issue by jiyinyiyong** [jw2013/elixir-china#55]

**Comment by jiyinyiyong** [comment]
创建了微博, 希望论坛可以提供一下 RSS 以便 IFTTT 转发 http://weibo.com/elixircn

**Comment by jw2013** [comment]
@jiyinyiyong 你有没有兴趣帮忙做一下RSS哈？？

:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by jiyinyiyong** [comment]
我现在对 Elixir 了解不够深, 而且经历还在前端, @lidashuang 可以帮忙看下吗?

**Comment by lidashuang** [comment]
@jiyinyiyong 周末看下

**Comment by lidashuang** [comment]
#59 @jiyinyiyong @jw2013
