### ISSUE TITLE
when run mix elixir-china.run occur an error

### ISSUE THREAD

**Issue by halfcrazy** [jw2013/elixir-china#57]
▶ mix elixir-china.server                             
==> bcrypt (compile)
Compiling c_src/async_queue.c
In file included from c_src/async_queue.c:32:0:
c_src/async_queue.h:45:21: fatal error: erl_nif.h: No such file or directory
 #include <erl_nif.h>
                     ^
compilation terminated.
ERROR: compile failed while processing /home/qwerty/workspace/elixir-china/deps/bcrypt: rebar_abort
** (Mix) Could not compile dependency bcrypt, /home/qwerty/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile bcrypt

**Comment by lidashuang** [comment]
http://irc.programmingelixir.com/search/date?date=2015-01-03#1420284414

**Comment by halfcrazy** [comment]
@lidashuang THX
