### ISSUE TITLE
Marked 换行配置

### ISSUE THREAD

**Issue by jiyinyiyong** [jw2013/elixir-china#60]
问题是换行在 Markdown 中默认是被转成空格的, 一般中文论坛都把换行开起来.

编辑器使用了 marked 但没有配置关于换行和 gfm 的选项.
这边引用的资源没有看到出处, 应该是在后边修改就可以的:
https://github.com/jw2013/elixir-china/blob/master/web/templates/layout/application.html.eex#L18

文档:
https://github.com/chjj/marked#usage

```js
marked.setOptions({
  renderer: new marked.Renderer(),
  gfm: true,
  breaks: false,
});
```

**Comment by lidashuang** [comment]
建议改成后端渲染
